name: "scraping"
services:
  mongo:
    container_name: mongo_db
    image: "mongo:latest"
    ports:
      - "27017:27017"

  selenium:
    container_name: selenium
    image: "selenium/standalone-chromium:latest"
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"

  scraping:
    build: .
    environment:
      - EVERY_TIME_ID=ticktacktok135
      - EVERY_TIME_PASSWORD=park6240
      - MONGO_URL=mongodb://mongo_db:27017
      - REMOTE_DRIVER_URL=http://selenium:4444
  mongo-client:
    container_name: gitp-client
    image: "mongo-client:latest"
