name: "scraping"
services:
  mongo:
    container_name: mongo_db
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ybigta135

  selenium:
    container_name: selenium
    image: "selenium/standalone-chromium:latest"
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"

#  scraping:
#    build: .

