name: "scraping"
services:
  mongo:
    container_name: mongo_db
    image: "mongo:latest"
    ports:
      - "27017:27017"
#    networks:
#      - foo_network

  selenium:
    container_name: selenium
    image: "selenium/standalone-chromium:latest"
    shm_size: 2gb
#    networks:
#      - foo_network
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"

  scraping:
    build: .
#    networks:
#      - foo_network

#networks:
#  foo_network:
#    driver: bridge
